### PR TITLE
surface data for NEON sites

### PR DESCRIPTION
**Pull request by srweintraub**
@ddurden @wwieder surface data files for NEON sites, do these meet expectations? I added the necessary helper files so code should be fully reproducible. let me know if anything is missing.

### CODE REVIEW

**Comment by wwieder** [comment]
Thanks @srweintraub these look good to me.

One question, it helps us on the NCAR side if the lat and lon are identical in the met and surface data.  Ultimately we need longitude in degrees E (0-360), this is easy enough for us to change, but are the met data already converted?  
 
We don't need the .csv files uploaded to this repo do we?  I think @ddurden will put them into the Bucket so data are available online.

Finally, can we provide metadata with information on units here, notably C and N to avoid confusion?  These could be in the second row of each dataset or in a readme that also gets created with the .csv files?

**Comment by ddurden** [comment]
@srweintraub , the code looks great! I will update the function with the option to output to S3. @wwieder and @srweintraub , I can remove the .csv files and consolidate the Lat and Lon coordinates while I'm adding the S3 output functionality. 

@wwieder , do you have a preference for the two units options?

**Comment by wwieder** [comment]
Assuming all these surface datasets are going to live in the same
directory, maybe it makes more sense to just have a README with metadata?
Would users grabbing data off the bucket need to know the URL for this
file, or could it be downloaded if someone grabbed the whole "directory"?

**Comment by ddurden** [comment]
@wwieder , users would need the URL or path to the metadata file.

**Comment by ddurden** [comment]
fieldName | description | dataType | units
-- | -- | -- | --
biogeoBottomDepth | Bottom depth of the biogeochemistry sample | real | centimeter
biogeoTopDepth | Top depth of the biogeochemistry sample | real | centimeter
bulkDensBottomDepth | Bottom depth of the bulk density sample | real | centimeter
bulkDensExclCoarseFrag | Bulk density of soil excluding coarse fragments (>2 mm) | real | gramsPerCubicCentimeter
bulkDensTopDepth | Top depth of the bulk density sample | real | centimeter
carbonTot | Total carbon concentration of the <2 mm fraction | real | gramsPerKilogram
clayTotal | Total clay (<0.002 mm) content on a weight basis of the <2 mm   fraction | real | percent
coarseFrac2to20 | Coarse fragment (2-20 mm) content of the <20 mm size fraction of the   biogeochemistry soil sample | real | gramsPerKilogram
coarseFrag2To5 | Coarse fragment (2-5 mm) content of the <20 mm size fraction of the   biogeochemistry soil sample | real | gramsPerKilogram
coarseFrag5To20 | Coarse fragment (5-20 mm) content of the <20 mm size fraction of the   biogeochemistry soil sample | real | gramsPerKilogram
decimalLatitude | The geographic latitude (in decimal degrees, WGS84) of the geographic   center of the reference area | real | decimalDegree
decimalLongitude | The geographic longitude (in decimal degrees, WGS84) of the geographic   center of the reference area | real | decimalDegree
domainID | Unique identifier of the NEON domain | string | NA
dominantPlants_Tower | The most dominant plant species found at the site | string | NA
ecoregionWWF_Megapit | The ecoregion at the site | string | NA
ecosystemType_Megapit | The predominant ecosystem type found at the site | string | NA
elevation | Elevation (in meters) above sea level | real | meter
horizonName | Soil horizon name | string | NA
landCover_Megapit | The landcover type found at the site | string | NA
nitrogenTot | Total nitrogen concentration of the <2 mm fraction | real | gramsPerKilogram
phH2o | pH of the <2 mm fraction in water | real | pH
sandTotal | Total sand (0.047-2 mm) content on a weight basis of the <2 mm   fraction | real | percent
siltTotal | Total silt (0.002-0.047 mm) content on a weight basis of the <2 mm   fraction | real | percent
siteID | NEON site code | string | NA

**Comment by ddurden** [comment]
@wwieder , does this format work for the meta file?

**Comment by srweintraub** [comment]
@ddurden thanks for updating the code! So shall I simply delete the csv files from the GitHub folder? The metadata you shared above looks good (I assume you mostly pulled from this file: GitHub/NCAR-NEON/surfaceData/variables.megapit.00096.csv), but a few of the 'derived' variables are not correctly defined and/or the units are not correct. How can I provide edits?

**Comment by ddurden** [comment]
@srweintraub , I'm modified the code and put in #29 .

**Comment by wwieder** [comment]
Meta data looks good

**Pull request merged**
