### PR TITLE
Update create.surface.data.R

### PR DESCRIPTION
**Pull request by srweintraub**
@ddurden ok, the 'local' and 'sw' options work for me, so if everything still works for you re the ECS workflow this code should be set. Please try and confirm. I updated definitions in the 'varMetaAdd' table so please re-push that to ECS.

### CODE REVIEW

**Comment by srweintraub** [comment]
oh yeah, did you update the lat/long stuff like Will wanted? I wasn't too clear exactly what was needed...

**Comment by ddurden** [comment]
@srweintraub , looks great! I will rerun to push the updates to ECS.

I can fix the Lat and Lon. @wwieder do you want the tower Lat and Lon coordinates instead of the megapit coordinates or just to convert these Lon to degrees East (+ 360)?

**Comment by wwieder** [comment]
good catch.  can the surface coordinate lat-lon be the same coords and the
tower that you're providing with the met data, Dave?
- maybe note this in the documentation too to clarify?

**Comment by ddurden** [comment]
@wwieder , yeah I can grab that metadata from another location. I'll name it differently and put it in the object description.

**Pull request merged**
